__author__ = 'ARJ'

## DEFAULT SECTION
NOTIFY_EMAIL = "DEFAULT.notify_email"
CORES = "DEFAULT.cores"
GENOME = "DEFAULT.genome"
TRANSCRIPT_GTF = "DEFAULT.transcripts_gtf"
TRANSCRIPT_GTF_MASK = "DEFAULT.transcripts_gtf_mask"

BCFTOOLS_BIN = 'BCFTOOLS.bin'

BCBIO_BACKUP = 'DEFAULT.bcbio_backup'

CUTADAPT_BIN = 'CUTADAPT.bin'
CUTADAPT_ADAPTERS = 'CUTADAPT.adapters'

CUFFLINKS_BIN = 'CUFFLINKS.bin'

DEFUSE_CONFIG = "DEFUSE.config"
DEFUSE_CORES = "DEFUSE.cores"
DEFUSE_DATA_DIR = "DEFUSE.data_dir"


MUTREPORT_CANCERGENES = 'MUTREPORT.cancer_gene_lists'
MUTREPORT_CGC = 'MUTREPORT.cgc'

POPVAR_EXACSNP_BED = 'POPVAR.pop_exacsnps_bed'
POPVAR_COSMIC_BED = 'POPVAR.pop_cosmicrec_bed'

QUALIMAP_BIN = 'QUALIMAP.bin'

RNASEQC_JAR = 'RNASEQC.jar'

SAMBAMBA_BIN = 'SAMBAMBA.bin'

SAMTOOLS_BIN = 'SAMTOOLS.bin'

STAR_BIN = 'STAR.bin'
STAR_CORES = 'STAR.cores'
STAR_GENOME_DIR = 'STAR.genome_dir'


TARGET_REGIONS = 'TARGET_REGIONS'
